name: benchmarks

on:
  push:
    branches:
      - main

jobs:
  benchmark:
    name: Report benchmarks for Qi forms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - name: Install Package and its Dependencies
        run: make install
      - name: Run benchmark
        shell: 'bash --noprofile --norc -eo pipefail {0}'
        run: make report-benchmarks | tee benchmarks.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Qi Benchmarks
          tool: 'customSmallerIsBetter'
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: benchmarks
          output-file-path: benchmarks.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
